# Generated by Django 4.1 on 2022-08-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date_costs',
            field=models.DateTimeField(verbose_name='date cost'),
        ),
        migrations.AlterField(
            model_name='profits',
            name='date_profit',
            field=models.DateTimeField(verbose_name='date to profits'),
        ),
    ]
