# Generated by Django 4.1 on 2022-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_costs_date_costs_alter_profits_date_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date_costs',
            field=models.DateField(verbose_name='date cost'),
        ),
        migrations.AlterField(
            model_name='profits',
            name='date_profit',
            field=models.DateField(verbose_name='date to profits'),
        ),
    ]
